<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <IncludePath>A:\lib\SDL3-3.2.6\include;A:\lib;$(SolutionDir)\src;$(IncludePath)</IncludePath>
    <ExternalIncludePath>A:\lib\SDL3-3.2.6\include;A:\lib;$(ExternalIncludePath)</ExternalIncludePath>
    <LibraryPath>A:\lib\SDL3-3.2.6\lib\x64;$(LibraryPath)</LibraryPath>
    <RunCodeAnalysis>true</RunCodeAnalysis>
    <EnableMicrosoftCodeAnalysis>false</EnableMicrosoftCodeAnalysis>
    <EnableClangTidyCodeAnalysis>true</EnableClangTidyCodeAnalysis>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level4</WarningLevel>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <TreatWarningAsError>true</TreatWarningAsError>
      <LanguageStandard>stdcpp23</LanguageStandard>
      <TreatAngleIncludeAsExternal>true</TreatAngleIncludeAsExternal>
      <ExternalWarningLevel>TurnOffAllWarnings</ExternalWarningLevel>
      <RuntimeTypeInfo>false</RuntimeTypeInfo>
      <ConformanceMode>true</ConformanceMode>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <DisableAnalyzeExternal>true</DisableAnalyzeExternal>
      <Optimization>Disabled</Optimization>
      <WholeProgramOptimization>false</WholeProgramOptimization>
      <DiagnosticsFormat>Classic</DiagnosticsFormat>
      <SDLCheck>true</SDLCheck>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>